support empty target chunks for empty files I've already seen this happen in practice like 20 different times. I'm keeping track of bad UX because I actually use hnt-edit. I've only ran aider like once, where I needed to modify hnt-edit while hnt-edit had a fatal bug I think Or maybe just to compare them on one edit that hnt-edit was failing on

diff --git a/edit/build b/edit/build
--- a/edit/build
+++ b/edit/build
@@ -11,6 +11,14 @@ then
 	cd -
 fi
 
+if ! which hnt-escape > /dev/null 2>&1
+then
+	echo "build: hnt-escape not found. compiling..."
+	cd ../llm
+	./build
+	cd -
+fi
+
 if ! which llm-pack > /dev/null 2>&1
 then
 	echo "build: llm-pack not found. compiling..."
