rename hnt --> hnt-llm

diff --git a/edit/build b/edit/build
--- a/edit/build
+++ b/edit/build
@@ -3,10 +3,10 @@
 # Change to directory where build script is located
 cd "$(dirname "$0")"
 
-if ! which hnt > /dev/null 2>&1
+if ! which hnt-llm > /dev/null 2>&1
 then
-	echo "build: hnt not found. compiling..."
-	cd ../hnt
+	echo "build: hnt-llm not found. compiling..."
+	cd ../llm
 	./build
 	cd -
 fi
