install hlmd-st as part of hnt-edit if possible

diff --git a/edit/build b/edit/build
--- a/edit/build
+++ b/edit/build
@@ -3,6 +3,19 @@
 # Change to directory where build script is located
 cd "$(dirname "$0")"
 
+if ! which hlmd-st > /dev/null 2>&1
+then
+	if which uv > /dev/null 2>&1
+	then
+		echo "build: uv installed but hlmd-st not found. installing..."
+		cd ../fmt/highlight
+		./build
+		cd -
+	else
+		echo "build: not installing hldm-st because uv not found. lol what are you doing"
+	fi
+fi
+
 if ! which hnt-llm > /dev/null 2>&1
 then
 	echo "build: hnt-llm not found. compiling..."
diff --git a/fmt/highlight/build b/fmt/highlight/build
--- a/fmt/highlight/build
+++ b/fmt/highlight/build
@@ -1,4 +1,11 @@
 #!/bin/sh -e
+
+if ! which uv > /dev/null 2>&1
+then
+	echo "build: uv is required"
+	exit 1
+fi
+
 cd "$(dirname "$0")"
 
 f=/tmp/hlmd-st
