make build script compile other deps

diff --git a/edit/build b/edit/build
--- a/edit/build
+++ b/edit/build
@@ -1,5 +1,24 @@
 #!/bin/sh -e
 
+# Change to directory where build script is located
+cd "$(dirname "$0")"
+
+if ! which hnt > /dev/null 2>&1
+then
+	echo "build: hnt not found. compiling..."
+	cd ../hnt
+	./build
+	cd -
+fi
+
+if ! which llm-pack > /dev/null 2>&1
+then
+	ehco "build: llm-pack not found. compiling..."
+	cd llm-pack
+	./build
+	cd -
+fi
+
 prompts_dir=$XDG_CONFIG_HOME/hinata/prompts
 bin=/usr/local/bin/
 
